import { FnInput, FormArgs, FormHelper, InputOption, StringBool } from "./types";
declare function username(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function password(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function otp(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function ip(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function lowerSnakeCase(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function port(...opts: Partial<InputOption<number>>[]): FnInput<number>;
declare function string(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function number(...opts: Partial<InputOption<number>>[]): FnInput<number>;
declare function boolean(...opts: Partial<InputOption<StringBool>>[]): FnInput<StringBool>;
declare function objectId(...opts: Partial<InputOption<string>>[]): FnInput<string>;
declare function form<INPUT>(opts: FormArgs<INPUT>): FormHelper<INPUT>;
declare const _default: {
    username: typeof username;
    password: typeof password;
    ip: typeof ip;
    port: typeof port;
    otp: typeof otp;
    string: typeof string;
    number: typeof number;
    objectId: typeof objectId;
    boolean: typeof boolean;
    lowerSnakeCase: typeof lowerSnakeCase;
    form: typeof form;
};
export default _default;
